# Generated by Django 5.2.12 on 2026-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('anons', models.CharField(max_length=255, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Maqola')),
                ('date', models.DateTimeField(verbose_name='Nashr etilgan sana')),
            ],
        ),
    ]
